### ISSUE TITLE
Functionality in source that is not described in README.

### ISSUE THREAD

**Issue by KristofferC** [kmsquire/Logging.jl#14]
By looking through the code I noticed this package has much more functionality than what is documented. Like how you can make several instances of the logger type and let them have parents, and how you can print to a log file with a specific logger etc.

Is that because of lack of time or because the other functions are not stable? They seemed to work fine for me.

**Comment by kmsquire** [comment]
Thanks for bringing this up.  I think that I didn't have much time when I added those features (a while ago), and in particular didn't test them that much.  After that, I just forgot. 

Any chance you can create a pull request with some docs?  Even if it isn't complete or perfect, it would push things in the right direction.

**Comment by KristofferC** [comment]
Yes, it will probably take a while since I am a bit busy but I will try to make some time for it.
