### ISSUE TITLE
Julia .4 Deprecated Base Classes

### ISSUE THREAD

**Issue by philipithomas** [kmsquire/Logging.jl#24]
It looks like "Base.Foo" is being replaced by "AbstractFoo". 

I might be able to work on this later today, but opening this for tracking.

**Comment by jskDr** [comment]
@philipithomas Thank you. It is so welcome since it is related to other libraries such as Mocha.jl.

**Comment by jskDr** [comment]
How's going on this issue? I still have warning to use other package which uses logging.jl.
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/jamessungjinkim/.julia/v0.4/Logging/src/Logging.jl:24
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/jamessungjinkim/.julia/v0.4/Logging/src/Logging.jl:24
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/jamessungjinkim/.julia/v0.4/Logging/src/Logging.jl:24
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/jamessungjinkim/.julia/v0.4/Logging/src/Logging.jl:40
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/jamessungjinkim/.julia/v0.4/Logging/src/Logging.jl:40
WARNING: Base.String is deprecated, use AbstractString instead.
  likely near /home/jamessungjinkim/.julia/v0.4/Logging/src/Logging.jl:40

**Comment by philipithomas** [comment]
We actually delayed our Julia .4 deployment due to so many issue and deprecations. Because of this , I haven't had a chance to start on this issue

**Comment by aviks** [comment]
This has been fixed by #23 . Just need to tag a new version.

**Comment by aviks** [comment]
Logging `v0.2.0` has now been released with these fixes.
